Repository dtugroupd/RoomLocatorWebapp, pull requests merged in 2019-11, with the labels that each got.

#40 Feature/manage surveys
  src/app/actions/mazemap.action.ts
  src/app/actions/survey.actions.ts
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/create-survey/create-survey.component.html
  src/app/create-survey/create-survey.component.scss
  src/app/create-survey/create-survey.component.ts
  src/app/feedback-button/feedback-button.component.html
  src/app/feedback-button/feedback-button.component.scss
  src/app/feedback-button/feedback-button.component.ts
  src/app/feedback-smiley-row/feedback-smiley-row.component.html
  src/app/feedback-smiley-row/feedback-smiley-row.component.scss
  src/app/feedback-smiley-row/feedback-smiley-row.component.ts
  src/app/feedback/feedback.component.html
  src/app/feedback/feedback.component.scss
  src/app/feedback/feedback.component.ts
  src/app/manage-surveys/manage-surveys.component.html
  src/app/manage-surveys/manage-surveys.component.scss
  src/app/manage-surveys/manage-surveys.component.spec.ts
  src/app/manage-surveys/manage-surveys.component.ts
  src/app/mazemap/mazemap.component.html
  src/app/mazemap/mazemap.component.scss
  src/app/mazemap/mazemap.component.ts
  src/app/models/mazemap.model.ts
  src/app/services/DynamicComponentService.ts
  src/app/services/base.service.ts
  src/app/services/mazemap.service.ts
  src/app/services/survey.service.ts
  src/app/states/mazemap.state.ts
  src/app/states/survey.state.ts
  src/app/status-button-menu/status-button-menu.component.html
  src/app/status-button-menu/status-button-menu.component.ts
  src/app/status-button/status-button.component.ts
  src/app/survey-list-item/survey-list-item.component.html
  src/app/survey-list-item/survey-list-item.component.scss
  src/app/survey-list-item/survey-list-item.component.spec.ts
  src/app/survey-list-item/survey-list-item.component.ts
  src/app/survey/survey.component.html
  src/app/survey/survey.component.ts
Labels: feature, frontend

#43 Download survey answers from survey management.
  package.json
  src/app/_services/survey.service.ts
  src/app/components/survey-management/survey-management.component.html
  src/app/components/survey-management/survey-management.component.ts
Labels: feature, frontend

#44 Feature/add user
  src/app/_actions/login.actions.ts
  src/app/_actions/user.actions.ts
  src/app/_services/mazemap.service.ts
  src/app/_states/login.state.ts
  src/app/_states/mazemap.state.ts
  src/app/_states/user.state.ts
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/auth/validate/validate.component.ts
  src/app/components/login-button/login-button.component.ts
  src/app/components/mazemap/mazemap.component.ts
  src/app/components/roles-view/roles-view.component.spec.ts
  src/app/components/roles-view/roles-view.component.ts
  src/app/models/login/login.model.ts
  src/app/models/login/user.model.ts
  src/app/models/mazemap/coordinates.model.ts
Labels: feature, frontend

#45 Save .csv content blob with correct encoding.
  src/app/_services/survey.service.ts
Labels: frontend

#53 Feature/fix login guards
  package.json
  src/app/_actions/token.actions.ts
  src/app/_actions/user.actions.ts
  src/app/_services/auth-guard.service.ts
  src/app/_services/auth.service.ts
  src/app/_services/login.service.ts
  src/app/_states/token.state.ts
  src/app/_states/user.state.ts
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.component.scss
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/auth/validate/validate.component.ts
  src/app/components/login-button/login-button.component.spec.ts
  src/app/components/login-button/login-button.component.ts
  src/app/components/roles-view/roles-view.component.html
  src/app/components/roles-view/roles-view.component.ts
  src/app/interceptors/tokenInterceptor.ts
  src/app/models/login/user.model.ts
  src/themes.scss
Labels: bug, feature

#58 Update state with created surveyAnswer resource. Handle error.
  src/app/_actions/survey.actions.ts
  src/app/_services/survey.service.ts
  src/app/_states/survey.state.ts
  src/app/components/survey-feedback/survey-feedback.component.ts
  src/app/components/survey-management/survey-management.component.html
  src/app/components/survey-management/survey-management.component.ts
Labels: bug, frontend

#55 Add '/' after dtu at the redirect url for SSO
  src/app/_services/auth.service.ts
Labels: bug

#61 Remove submit() onclick. Button automatically submits form.
  src/app/components/survey-create/survey-create.component.html
  src/app/components/survey-create/survey-create.component.ts
Labels: bug, frontend

#63 Show authorized routes
  src/app/app.component.html
  src/app/app.component.scss
  src/app/app.component.ts
Labels: frontend

#69 Enforce service state architecture
  src/app/_actions/mazemap.actions.ts
  src/app/_actions/survey.actions.ts
  src/app/_services/survey.service.ts
  src/app/_states/mazemap.state.ts
  src/app/_states/survey.state.ts
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/components/survey-create/survey-create.component.ts
  src/app/components/survey-feedback/survey-feedback.component.ts
  src/app/components/survey-management/survey-management.component.ts
Labels: frontend

#70 Use old CampusNet Login
  package.json
  src/app/_actions/token.actions.ts
  src/app/_actions/user.actions.ts
  src/app/_services/_guards/auth-guard.service.ts
  src/app/_services/auth.service.ts
  src/app/_services/login.service.ts
  src/app/_states/token.state.ts
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/auth/login/login.component.html
  src/app/auth/login/login.component.scss
  src/app/auth/login/login.component.spec.ts
  src/app/auth/login/login.component.ts
  src/app/auth/validate/validate.component.ts
  src/app/interceptors/tokenInterceptor.ts
  src/app/models/login/user.model.ts
Labels: feature, frontend
