Repository dtugroupd/RoomLocatorWebapp, pull requests merged in 2019-10, with the labels that each got.

#15 Feature/#3 display mazemap
  .gitignore
  package-lock.json
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.module.ts
  src/app/mazemap/mazemap.component.html
  src/app/mazemap/mazemap.component.scss
  src/app/mazemap/mazemap.component.spec.ts
  src/app/mazemap/mazemap.component.ts
  src/assets/sensor-icon.png
  src/index.html
Labels: feature

#16 Setup simple SSO integration
  README.md
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/auth/validate/validate.component.spec.ts
  src/app/auth/validate/validate.component.ts
  src/app/login-button/login-button.component.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: feature

#22 Http client base url depends on environment.
  src/app/services/mazemap.service.ts
Labels: frontend

#23 Feature/survey feedback
  package.json
  src/app/app.module.ts
  src/app/create-survey/create-survey.component.html
  src/app/create-survey/create-survey.component.scss
  src/app/create-survey/create-survey.component.spec.ts
  src/app/create-survey/create-survey.component.ts
  src/app/feedback-smiley-row/feedback-smiley-row.component.html
  src/app/feedback-smiley-row/feedback-smiley-row.component.scss
  src/app/feedback-smiley-row/feedback-smiley-row.component.spec.ts
  src/app/feedback-smiley-row/feedback-smiley-row.component.ts
  src/app/feedback/feedback.component.html
  src/app/feedback/feedback.component.scss
  src/app/feedback/feedback.component.spec.ts
  src/app/feedback/feedback.component.ts
  src/app/mazemap/mazemap.component.scss
  src/app/mazemap/mazemap.component.ts
  src/app/models/mazemap.model.ts
  src/app/services/DynamicComponentService.ts
  src/app/services/base.service.ts
  src/app/services/mazemap.service.ts
  src/app/services/survey.service.ts
  src/app/survey/survey.component.html
  src/app/survey/survey.component.scss
  src/app/survey/survey.component.spec.ts
  src/app/survey/survey.component.ts
Labels: feature, frontend

#24 Hotfix/smiley icon interaction
  src/app/feedback-smiley-row/feedback-smiley-row.component.html
Labels: frontend

#26 Move survey feedback entry to own accessible button, add additional l…
  src/app/actions/mazemap.action.ts
  src/app/app.component.html
  src/app/app.component.scss
  src/app/app.module.ts
  src/app/feedback-button/feedback-button.component.html
  src/app/feedback-button/feedback-button.component.scss
  src/app/feedback-button/feedback-button.component.spec.ts
  src/app/feedback-button/feedback-button.component.ts
  src/app/feedback/feedback.component.ts
  src/app/mazemap/mazemap.component.html
  src/app/mazemap/mazemap.component.scss
  src/app/mazemap/mazemap.component.ts
  src/app/states/mazemap.state.ts
  src/app/survey/survey.component.html
  src/app/survey/survey.component.ts
Labels: feature, frontend

#27 Disabled map interaction.
  src/app/mazemap/mazemap.component.ts
Labels: feature, frontend

#28 Feature/disable map interaction
  src/app/mazemap/mazemap.component.ts
Labels: frontend

#29 Feature/show section marker
  src/app/feedback-button/feedback-button.component.ts
  src/app/mazemap/mazemap.component.ts
  src/app/models/mazemap.model.ts
  src/app/services/DynamicComponentService.ts
  src/assets/coffee.svg
  src/assets/databar.svg
  src/assets/group-study.svg
  src/assets/information.svg
  src/assets/lounge.svg
  src/assets/sensor-icon.png
  src/assets/stage.svg
  src/assets/study.svg
Labels: feature, frontend

#30 Re-enabled max/min zoom on map.
  src/app/mazemap/mazemap.component.ts
Labels: frontend

#31 Feature/general section feedback
  src/app/actions/mazemap.action.ts
  src/app/app.component.html
  src/app/app.component.ts
  src/app/create-survey/create-survey.component.ts
  src/app/feedback-button/feedback-button.component.html
  src/app/feedback-button/feedback-button.component.scss
  src/app/feedback-button/feedback-button.component.ts
  src/app/login-button/login-button.component.ts
  src/app/mazemap/mazemap.component.html
  src/app/mazemap/mazemap.component.scss
  src/app/mazemap/mazemap.component.ts
  src/app/services/DynamicComponentService.ts
  src/app/states/mazemap.state.ts
  src/app/survey/survey.component.html
  src/app/survey/survey.component.ts
Labels: feature, frontend

#32 Feature/ui general
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/calendarview/calendarview.component.html
  src/app/calendarview/calendarview.component.scss
  src/app/calendarview/calendarview.component.spec.ts
  src/app/calendarview/calendarview.component.ts
  src/app/feedback-smiley-row/feedback-smiley-row.component.html
  src/app/mazemap/mazemap.component.html
  src/app/mazemap/mazemap.component.scss
  src/app/mazemap/mazemap.component.ts
  src/app/status-button/status-button.component.html
  src/app/status-button/status-button.component.scss
  src/app/status-button/status-button.component.spec.ts
  src/app/status-button/status-button.component.ts
Labels: feature, frontend

#33 Feature/change general feedback ui
  src/app/app.module.ts
  src/app/create-survey/create-survey.component.html
  src/app/feedback-button/feedback-button.component.html
  src/app/feedback-button/feedback-button.component.scss
  src/app/feedback-button/feedback-button.component.ts
  src/app/mazemap/librarySections.js
  src/app/mazemap/mazemap-helper.ts
  src/app/mazemap/mazemap.component.html
  src/app/mazemap/mazemap.component.scss
  src/app/mazemap/mazemap.component.ts
  src/app/states/mazemap.state.ts
  src/app/status-button-menu/status-button-menu.component.html
  src/app/status-button-menu/status-button-menu.component.scss
  src/app/status-button-menu/status-button-menu.component.spec.ts
  src/app/status-button-menu/status-button-menu.component.ts
  src/app/status-button/status-button.component.scss
  src/app/status-button/status-button.component.ts
Labels: feature, frontend

#34 Survey with title
  src/app/app.module.ts
  src/app/create-survey/create-survey.component.html
  src/app/create-survey/create-survey.component.scss
  src/app/create-survey/create-survey.component.ts
  src/app/models/mazemap.model.ts
  src/app/services/survey.service.ts
Labels: frontend
