Repository dtugroupd/RoomLocatorWebapp, pull requests merged in 2019-12, with the labels that each got.

#68 feedback_frontend ny branch forfra
  src/app/_actions/feedback.actions.ts
  src/app/_services/feedback.service.ts
  src/app/_states/feedback.state.ts
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/components/mazemap/mazemap.component.ts
  src/app/components/status-button-menu/status-button-menu.component.html
  src/app/components/status-button-menu/status-button-menu.component.scss
  src/app/components/status-button-menu/status-button-menu.component.ts
  src/app/models/feedback/feedback.model.ts
Labels: feature, frontend

#92 Fix race condition, hide feedback button if no survey available
  src/app/components/mazemap/mazemap.component.ts
  src/app/components/survey-feedback-button/survey-feedback-button.component.html
  src/app/components/survey-management/survey-management.component.ts
Labels: bug

#95 show feedback has been redesigned a bit
  src/app/components/admin_page/admin-page.component.ts
  src/app/components/showFeedback/show-feedback.component.html
Labels: feature, frontend

#113 Changed Danish placeholder text to English
  src/app/components/event-create/event-create.component.html
  src/app/components/event-update/event-update.component.html
Labels: frontend

#114 Hotfix/addevent success
  src/app/_actions/event.actions.ts
  src/app/_actions/mazemap.actions.ts
  src/app/_states/event.state.ts
  src/app/_states/mazemap.state.ts
Labels: frontend
